# Installing python, uv and setting up mise.toml

# We can do this with mise use or create the mise.toml file
# mise use python@3.13

[tools]
k3d = "latest"
k9s = "latest"
kubectl = "latest"
pre-commit = "latest"
python = "3.13"
ruff = "latest"
trivy = "latest"
uv = "latest"

[settings]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[env]
APP_REPO = 'cd-playground'
GITOPS_REPO = 'cd-playground-gitops'

[hooks]#this  will be run whenever we enter a project, when we ssh into the container
#enter = "bash ./scripts/setup_project"
enter = "sh ./scripts/setup_project_sh"

[tasks.k8s-setup-local]
description = "Set up a basic Kubernetes cluster for development that builds the local images and applies them"
run = "bash ./kubernetes/setup_cluster_local"

[tasks.k8s-setup-minimal]
description = "Set up a basic minimal Kubernetes cluster"
run = "bash ./kubernetes/setup_minimal_cluster_local"
