#!/bin/sh

if ! command -v cz >/dev/null; then
  if [ "$DEVPOD" = "true" ]; then
    git config --global push.autoSetupRemote true
    git config --global --add safe.directory /workspaces/cd-playground
    #pip install --user pipx
    #pipx install commitizen
    uv tool install commitizen
    pre-commit install
    pre-commit install --hook-type commit-msg
  fi
fi
