name: Backend test

on:
  pull_request:


jobs:
  checkout:
    runs-on: ubuntu_latest
    outputs:
      should_run: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
      #enables conditional actions for jobs
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
        #check if those paths are changed in any way
          filters: |
            backend:
              - 'src/backend/**'
              - '.github/workflows/backend-tests.yaml'

  test:
    name: Test Backend
    needs: check_paths
    if: ${{ needs.check_paths.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: |
          uv sync --locked --dev

      - name: Lint with Ruff
        run: |
          uv run ruff check --output-format=github --target-version=py313 src tests
          uv run ruff format --diff --check --target-version=py313 src tests
