name: Build Docker Image and push to GitHub

on:
  push:
    branches:
      - feat/docker-push-ghcr
    #tags:
    #  - backend*

permissions:
  contents: read
  packages: write

jobs:
  Docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: ./src/backend
      - name: build docker image
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io